import { Offer } from "../types/Offer";
const generateId = () => Math.random().toString(36).substr(2, 9);

export const data: Offer[] = [
  {
    id: generateId(),
    title: "Frontend Developer",
    description:
      "Build responsive web apps amsd samd. das. ad as a das dnas nad sad asd asm dmadssadmsa md asm dasdas dsa dmas masd mas dmdas dmas dmas dmas md asmd ams dmas d msefjsrjvnrsmanfesnifd awfiesnfies cja iocnae cjesncies. cieosnc jesi esesncj escnies cueacnae daec. ac aecnae cas canieancies cjes c escjnesinfcesjnce c e cjse jce sc esc esj cjesnesifiesmdaej c esc es cejsncjes cjes c esh esj cjesncesnicenscise c esc es ce sjcnesncesj ces cjk esjc esnc jesc escniesncjes cesciesncjse cjes jcsenifnje vsd ise cejsniencjes cjseces cjes cjes cjesncenscnsen cesvornjes ed adandas dsa d d d dasdnasidn asdasic jc djs cjsces.",
    location: "Remote",
    salary: 5000,
    status: "pending",
    dateAndTime: new Date().toISOString(),
    maxParticipants: 20,
    owner: "Company A",
    chosenCandidate: "",
    candidates: ["user1", "user2"],
    tags: [
      { id: generateId(), name: "React" },
      { id: generateId(), name: "TypeScript" },
      { id: generateId(), name: "JavaScript" },
      { id: generateId(), name: "Docker" },
      { id: generateId(), name: "Kubernetes" },
      { id: generateId(), name: "Java" },
      { id: generateId(), name: "Python" },
      { id: generateId(), name: "Scala" },
      { id: generateId(), name: "DevOps" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Backend Developer",
    description: "Develop APIs and services",
    dateAndTime: "2025-12-05T09:00:00Z",
    location: "New York",
    salary: 75000,
    status: "accepted",
    maxParticipants: 20,
    owner: "Company B",
    chosenCandidate: "user3",
    candidates: ["user3"],
    tags: [
      { id: generateId(), name: "Node.js" },
      { id: generateId(), name: "PostgreSQL" },
      { id: generateId(), name: "Kubernetes" },
      { id: generateId(), name: "Java" },
      { id: generateId(), name: "Python" },
      { id: generateId(), name: "Scala" },
      { id: generateId(), name: "DevOps" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "UI/UX Designer",
    description: "Design user interfaces and experiences",
    dateAndTime: "2025-12-10T09:00:00Z",
    location: "Remote",
    salary: 60000,
    status: "declined",
    maxParticipants: 20,
    owner: "Company C",
    chosenCandidate: "",
    candidates: ["user4", "user5"],
    tags: [
      { id: generateId(), name: "Figma" },
      { id: generateId(), name: "Adobe XD" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "DevOps Engineer",
    description: "Manage cloud infrastructure",
    dateAndTime: "2025-12-12T09:00:00Z",
    location: "San Francisco",
    salary: 90000,
    status: "accepted",
    maxParticipants: 20,
    owner: "Company D",
    chosenCandidate: "user6",
    candidates: ["user6"],
    tags: [
      { id: generateId(), name: "AWS" },
      { id: generateId(), name: "Docker" },
      { id: generateId(), name: "Kubernetes" },
      { id: generateId(), name: "Java" },
      { id: generateId(), name: "Python" },
      { id: generateId(), name: "Scala" },
      { id: generateId(), name: "DevOps" },
      { id: generateId(), name: "Kubernetes" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Data Scientist",
    description: "Analyze data and build ML models",
    dateAndTime: "2025-12-15T09:00:00Z",
    location: "Remote",
    salary: 85000,
    status: "pending",
    maxParticipants: 20,
    owner: "Company E",
    chosenCandidate: "",
    candidates: ["user7"],
    tags: [
      { id: generateId(), name: "Python" },
      { id: generateId(), name: "Machine Learning" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Product Manager",
    description: "Lead product development",
    dateAndTime: "2025-12-20T09:00:00Z",
    location: "London",
    salary: 80000,
    status: "pending",
    maxParticipants: 20,
    owner: "Company F",
    chosenCandidate: "",
    candidates: ["user8", "user9"],
    tags: [
      { id: generateId(), name: "Agile" },
      { id: generateId(), name: "Scrum" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Mobile Developer",
    description: "Build iOS and Android apps",
    dateAndTime: "2025-12-22T09:00:00Z",
    location: "Remote",
    salary: 75000,
    status: "accepted",
    maxParticipants: 20,
    owner: "Company G",
    chosenCandidate: "user10",
    candidates: ["user10"],
    tags: [
      { id: generateId(), name: "React Native" },
      { id: generateId(), name: "TypeScript" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "QA Engineer",
    description: "Test software and report bugs",
    dateAndTime: "2025-12-25T09:00:00Z",
    location: "Berlin",
    salary: 65000,
    status: "declined",
    maxParticipants: 20,
    owner: "Company H",
    chosenCandidate: "",
    candidates: ["user11"],
    tags: [
      { id: generateId(), name: "Testing" },
      { id: generateId(), name: "Selenium" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Marketing Specialist",
    description: "Create marketing campaigns",
    dateAndTime: "2025-12-28T09:00:00Z",
    location: "Remote",
    salary: 55000,
    status: "pending",
    maxParticipants: 20,
    owner: "Company I",
    chosenCandidate: "",
    candidates: ["user12"],
    tags: [
      { id: generateId(), name: "SEO" },
      { id: generateId(), name: "Content Marketing" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    title: "Support Engineer",
    description: "Provide technical support",
    dateAndTime: "2025-12-30T09:00:00Z",
    location: "Remote",
    salary: 50000,
    status: "accepted",
    maxParticipants: 20,
    owner: "Company J",
    chosenCandidate: "user13",
    candidates: ["user13", "user14"],
    tags: [
      { id: generateId(), name: "Customer Support" },
      { id: generateId(), name: "Troubleshooting" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
